In [1]:
import numpy as np
from array import array

In [4]:
matriz = np.array([[1.0,2],[3,4]])
matriz

array([[1., 2.],
       [3., 4.]])

In [6]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
print(matriz.dtype)
print(tensor.dtype)

float64
int32


In [16]:
matriz = np.array([[[1, 5, 3],[4, 5, 6]], [[1, 5, 3],[4, 5, 6]]])
print(matriz)
matriz.shape

[[[1 5 3]
  [4 5 6]]

 [[1 5 3]
  [4 5 6]]]


(2, 2, 3)

In [18]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.


  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/ae/d9/3741b344f57484b423cd22194025a8489992ad9962196a62721ef9980045/pandas-2.1.4-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tzdata>=2022.1 from https://files.pythonhosted.org/packages/a3/fb/52b62131e21b24ee297e4e95ed41eba29647dad0e0051a92bb66b43c70ff/tzdata-2023.4-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.5 MB 388.9 kB/s eta 0:00:27
   ---------------------------------------- 0.1/10.5 MB 651.6 kB/s eta 0:00:16
   ---------------------------------------- 0.1/10.5 MB 655.4 kB/s eta 0:0


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
import pandas as pd

In [21]:
arr_2 = np.full((5,2), 10)
arr_2

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [22]:
arr_3 = np.random.rand(4,2)
arr_3

array([[0.43914043, 0.51959275],
       [0.27000758, 0.91399848],
       [0.82656641, 0.20282935],
       [0.14852542, 0.39275465]])

In [23]:
arr_4 = np.random.randint(5, 20, size = (3, 3))
arr_4

array([[ 7, 18,  5],
       [ 8, 13,  5],
       [13, 14, 14]])

In [24]:
arr_4[1,1]

13

In [25]:
arr_4[0:2, 0:2]

array([[ 7, 18],
       [ 8, 13]])

In [26]:
arr_4[0:2, :]

array([[ 7, 18,  5],
       [ 8, 13,  5]])

In [27]:
arr = np.random.randint(5, 20, size = (3, 3))
arr

array([[17, 16, 18],
       [ 9,  5, 13],
       [18,  8,  9]])

In [30]:
arr.sum()

113

In [31]:
arr_5 = np.array(range(10,20))

In [32]:
pd.Series(arr_5)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [36]:
from datetime import datetime

In [39]:
df = pd.DataFrame(arr, columns=['a', 'b', 'c'])
df ['idade'] = [10, 20, 30]
df

a   b   c  idade
0  17  16  18     10
1   9   5  13     20
2  18   8   9     30

In [41]:
df1 = pd.DataFrame({'Nome': ['João', 'Maria'], 'Idade': [20, 50]})
df1

Nome  Idade
0   João     20
1  Maria     50

Exercícios

In [45]:
np.array([10, 20, 30, 40, 50, 60, 70, 80, 100])

array([ 10,  20,  30,  40,  50,  60,  70,  80, 100])

In [59]:
matriz2 = np.array([[0,3], [0,4], [5,0], [1,0], [8,1]])
matriz2

array([[0, 3],
       [0, 4],
       [5, 0],
       [1, 0],
       [8, 1]])

In [60]:
matriz2.min

<function ndarray.min>